module.exports={
    "mysql":{
        connectionLimit:100,
        host:'localhost',
        user:'root',
        password:'',
        database:'tenakatauni',
        debug:false
    },
    "port":3000,
    "aws":{
        AWS_ACCESS_KEY_ID:'',
        AWS_SECRET_ACCESS_KEY:''
    }
}